# serverless.yml

service: extractMetaData

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  app:
    handler: build/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - http:
          path: hello-world
          method: get